### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by esyjli** [jfkominsky/PyHab#2]
I tried to run the demo, but "Fatal Python error: (pygame parachute) Segmentation Fault" kept popping up and it wouldn't run. I can't figure out why :(

**Comment by jfkominsky** [comment]
Four quick questions:
1. Do any of the scripts in the psychopy demo menu work or do they all give
the same error?
2. What operating system are you using?
3. Which version of psychopy?
4. Are you running the demo with video or a no-stim version?

Most of the time this issue has to do with psychopy rather than my script
specifically, but I might be able to suggest some fixes.

**Comment by esyjli** [comment]
Thanks for the quick response!
1. They all give the same error
2. macOS Sierra Version 10.12.6
3. v1.85.3
4. demo with video

**Comment by jfkominsky** [comment]
OK, this is a PsychoPy issue, not PyHab. You may find some helpful info 
on discourse.psychopy.org, but one fix I have found useful is going into 
System preferences > Security > Accessibility and making sure PsychoPy 
is one of the apps that is allowed to take control of the computer. If 
that doesn't fix it, there are some threads on the PsychoPy discourse 
describing similar issues and fixes people have tried. Good luck!

**Comment by esyjli** [comment]
I'll try that. Thank you!
